#!/bin/bash
set -euo pipefail

PATTERN="$BUILDKITE_PLUGIN_SPELLCHECK_PATTERN"

echo "--- Checking files for misspelt words"

WORDS=()

for i in $(find . -name $PATTERN)
do
  WORDS+=$(cat $i |docker run -i starefossen/aspell list)
done

echo -e "Found the following misspelt words: ${WORDS}"

buildkite-agent annotate "Found the following misspelt words: ${WORDS}"
